//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peluditos.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int idMascota { get; set; }
        public int idAdoptante { get; set; }
        public int idInstitucion { get; set; }
    
        public virtual adoptante adoptante { get; set; }
        public virtual mascota mascota { get; set; }
        public virtual instituciones instituciones { get; set; }
    }
}
