//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peluditos.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mascota()
        {
            this.agenda = new HashSet<agenda>();
        }
    
        public int id { get; set; }
        public string nombres { get; set; }
        public string edad { get; set; }
        public string tamaño { get; set; }
        public string controlMedico { get; set; }
        public string ciudadReferencia { get; set; }
        public string ubicacion { get; set; }
        public byte[] foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
    }
}
